### ISSUE TITLE
Running .tagged() on a node

### ISSUE THREAD

**Issue by KINKCreative** [Stefdv/gun-tag#3] opened 2019-12-31 19:19 UTC
I can't tell from the docs, if that's the intended behavior, but I think the gun.tagged() is not behaving as expected when run on a node (not on root). For example, I am trying to do:

```
this.$gun.get('someitem').put({ title: 'SOME ITEM' })
this.$gun.get('someitem').tag([’tag1, ’tag2’])

//later then…
this.$gun
      .get('someitem')
      .tagged(r => {
        console.log(r)
      })
```

It doesn’t even run. I see the tags property is there on the node, e.g. `gun.get('someitem').get('tags')` but I just can’t get the list with `.tagged()` I’ve tried with `tagged().once( … )` as well.

I would assume the ideal would be to get a callback which:
- if no params are passed `gun.get('someitem').tagged()` would return all tags on that node
- if a param is passed, filter out and list only the child tags (as described in the docs)

I am relying on my own getter at the moment, but I am not sure how I can filter out those that have been untagged - as you note in the docs, the tags will show in the tags property even after untagged, but it may not necessarily mean that it's active.

**Comment by Stefdv** [comment] 2020-01-03 10:24
The usage should be 
```
 this.$gun.tagged('tag1',r=>{
                                 console.log(r)
})
```

**Comment by Stefdv** [comment] 2020-01-03 10:29
And if you want all items that are tagged to both 'tag1' and 'tag2' aka an intersect you should provide an Array to tagged
```
gun.intersect( ['tag1','tag2'],cb)
```

Please let me know if it's working for you

**Comment by Stefdv** [comment] 2020-01-07 19:36
I post a quick example here
```
// init gun
const gun = Gun()
const CONTACTS = gun.get('CONTACTS')

// let's create a SET with some people
// NOTE: we could tag the items right here like
//       `CONTACTS.set(gun.get('randomSoul01').put({name:'Alex',age:30}).tag('member')) `
// but for explaining we use a seperate step


  CONTACTS.set(gun.get('alex').put({name:'Alex',age:30}))
  CONTACTS.set(gun.get('alice').put({name:'Alice',age:28}))
  CONTACTS.set(gun.get('bob').put({name:'Bob',age:33}))
  CONTACTS.set(gun.get('charley').put({name:'Charly',age:21}))

// use listonce on the SET to get all contacts
// and tag them to be a member and assume they paid there contribution
// NOTE : gun.listonce actually puts the property '_soul' on the node
CONTACTS.listonce(obj=>{
  obj.list.forEach(item => {
    gun.get(item._soul).tag(['member','paid'])
  });
},1000)

// Now we can use gun-tagged to get all members
setTimeout(()=>{
  console.log('---------- get all members -----------')
  console.log('gun.tagged("member",cb)')

  gun.tagged('member',d=>{
    console.log(d.list)
  })

},1000)

setTimeout(()=>{
  console.log('---------- get all persons that paid -----------')
  console.log('gun.tagged("paid",cb)')

    gun.tagged('paid', d=>{
      console.log(d.list)
    })

  },2000)

setTimeout(()=>{
  console.log('---------- Bob did not pay  -----------')
  console.log('gun.get("bob").untag("paid")')

  gun.get('bob').untag('paid')

},3000)

setTimeout(()=>{
  console.log('---------- All persons that paid  -----------')
  console.log('gun.tagged("paid",cb)')

  gun.tagged('paid',d=>{
    console.log("No more Bob")
    console.log(d.list)
  })

},4000)

setTimeout(()=>{
  console.log('---------- Alex wants to be a contributor only, not a member  -----------')
  console.log('gun.get("alex").untag("member")')

  gun.get('alex').untag('member')

},5000)

setTimeout(()=>{
  console.log('---------- get all members -----------')
  console.log('gun.tagged("member",cb) ')

  gun.tagged('member',d=>{
    console.log('No more Alex ')
    console.log(d.list)
  })

},6000)

setTimeout(()=>{
  console.log('---------- use gun.intersect to get members that actually paid -----------')
  console.log('gun.intersect(["member","paid"],cb) ')
  // gun.intersect only returns an Array

  gun.intersect(['member','paid'],list=>{
    console.log('only Alice and Charly')
    console.log(list)
  })

},7000)
```

**Comment by Stefdv** [comment] 2020-01-07 22:36
Please note that for an intersect you'll have to use `gun.intersect(['tag1','tag2',...],cb) ` NOT gun.tagged() as i stated a few comments back ( edited that comment )

**Comment by Stefdv** [comment] 2020-01-11 09:28
I'm closing this issue , after all gun.tag does behave as intended.

**Closed as completed by Stefdv** 2020-01-11 09:28 UTC
